name: End2End Cypress WebApp

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Navigate to WebApp directory
        run: cd RentIT-Frontend/
      - name: Install project dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Start the application
        run: npm start &
      - name: Wait for the application to start
        run: sleep 10
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
