name: End2End Cypress WebApp

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'RentIT-Frontend/**'

## TODO: Some of the test will fail for the moment as the backend is not available on cloud
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: RentIT-Frontend
          build: yarn run build
          start: yarn start
          browser: chrome
