name: GitHub Actions Maven Build
on:
  push:
    branches: [ "main" ]
    paths:
      - 'RentIT/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'RentIT/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2
      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Step 3 - Have GitHub Actions Build Maven Project
        run: mvn -B package
      - name: Step 4 - Run project tests with maven
        run: mvn clean test
